### ISSUE TITLE
Justify text

### ISSUE THREAD

**Issue by reouvenzana** [mgmeyers/obsidian-california-coast-theme#100]
Hello, 

Sorry to ask for this here, but I'm not a CSS pro. What class should I modify in your theme to justify the text ? 

Thank you very much

**Comment by tim-hilde** [comment]
This allows for justification in preview mode: 

```
.cm-s-obsidian, .markdown-preview-view {
text-align: justify;
hyphens: auto;}
```

**Comment by reouvenzana** [comment]
Thank you ! That solves my issue.
