### ISSUE TITLE
I

### ISSUE THREAD

**Issue by u2003** [mgmeyers/obsidian-california-coast-theme#101]

**Comment by u2003** [comment]
<img width="1437" alt="image" src="https://user-images.githubusercontent.com/84957135/143836599-8b23cd09-f166-4e0c-9434-dca1cc7dd70a.png">
This is the actual appearance of my Obsidian after I apply this theme, but I think it's quite different from that of the demo. You can see the icons on the side bar… I don't know whether there is something amiss. I do hope you can help me with this.

More than Obliged!

**Comment by mgmeyers** [comment]
Hi @u2003, you'll need to install the `Style Settings` plugin to get the most out of this theme. Using that plugin, you can enable icons and many other customizations of the theme.

<img width="751" alt="Screen Shot 2021-11-29 at 10 17 01 AM" src="https://user-images.githubusercontent.com/2694747/143921428-068576b8-24d6-4b79-8d41-aeb6a3204954.png">

**Comment by u2003** [comment]
Thanks for your reply!! I’ve tried out and it hopefully works!! Thanks a lot!
