### ISSUE TITLE
[BUG] Empty space on embedded notes

### ISSUE THREAD

**Issue by WhiteNoiseDev** [mgmeyers/obsidian-california-coast-theme#102]
There is an unusual big space while embedding a note that has YAML front matter.

Thanks!

![image](https://user-images.githubusercontent.com/3163647/144690472-03c54e4c-5626-4622-bf71-b50d0ccf1489.png)

![image](https://user-images.githubusercontent.com/3163647/144690475-38df19a7-f652-473f-ac0f-608f0c6436d2.png)

**Comment by mgmeyers** [comment]
@WhiteNoiseDev I made some tweaks to embedded notes, can you see if this is still an issue for you?

**Comment by WhiteNoiseDev** [comment]
Looks fixed now. Thanks!
