### ISSUE TITLE
Is there a way to change the highlight color when in dark mode?

### ISSUE THREAD

**Issue by stanislavkozlovski** [mgmeyers/obsidian-california-coast-theme#107]
Currently, the theme highlights text in a brown-ish color (e.g CTRL+F, or `==text==`) with dark mode.

 I would like to modify this to be yellow like in the light theme.

1. Is it possible to add an option to modify this within the Style Settings plugin?
2. Would you be able to advise me which variable inside the .css I can hard-code to work around this until we have official support?

**Comment by mgmeyers** [comment]
Hi @stanislavkozlovski I've added some style settings to change the highlight color. Try updating the theme and let me know if these work for you.

**Comment by stanislavkozlovski** [comment]
👑 - you dropped this. It works great
