### ISSUE TITLE
Whiteline over sidebar in translucent mode

### ISSUE THREAD

**Issue by xidsyed** [mgmeyers/obsidian-california-coast-theme#108]
![image](https://user-images.githubusercontent.com/26184016/147858833-875cd5c4-747c-4b7f-a64a-813148b2b8dc.png)
 Do you see the white line up there?
I am using the hider plugin, ,but I have noticed it without it as well. Can't think of anything else that could be causing this

it comes and goes, as i resize and snap windows. i tried to come up with a pattern, but its totally random.  It usually appears when i snap window to the left using win+left/right arrow.

**Comment by mgmeyers** [comment]
Hmm, This isn't something I've been able to reproduce @xidsyed. What OS are you on?

**Comment by xidsyed** [comment]
windows 10. I am also using the hider plug in. Using windows 11 currently don't face it anymore

**Comment by mgmeyers** [comment]
Ok, thanks for letting me know. I'm going to close this for now. Let me know if you run into it again.
