### ISSUE TITLE
Trim Dataview columns 

### ISSUE THREAD

**Issue by zeltak** [mgmeyers/obsidian-california-coast-theme#109]
Hi, love this theme! thx for all your hard work!

one thing that is still a issue for me is the `Dataview` in `california coast`

there seems to be no word wrapping in table cells and it just looks really bad:

![image](https://user-images.githubusercontent.com/498410/147871377-2445d90a-408a-4e28-bf6d-51d17ea07524.png)

anyway to address this? any setting I've missed?

i saw the `minimal` theme released an update to address this as well in their V 4.3

> Trim Dataview columns Disables word wrapping in table cells, and trims long text

https://github.com/kepano/obsidian-minimal/releases/tag/4.3.0

thx so much again

Z

**Comment by mgmeyers** [comment]
@zeltak I've added two style settings that should help here. They apply to all tables, though, not just dataview:

<img width="745" alt="Screen Shot 2022-01-08 at 11 06 28 AM" src="https://user-images.githubusercontent.com/2694747/148656593-02ed45be-c1c4-44c6-8c33-cf8e59e00d18.png">

Let me know if this works for you

**Comment by zeltak** [comment]
wow wow wow!

this is awesome thx so much, its perfect now @mgmeyers 

love this theme so much :)

best and thx so much again

Z
