### ISSUE TITLE
Title bar

### ISSUE THREAD

**Issue by ze-kel** [mgmeyers/obsidian-california-coast-theme#11]
Currently title bar has issues. Back and forward buttons are gone and minimize\maximize\close buttons are pure white on light gray background.

Here's possible fix for bringing back the color

Line 1488
`.titlebar-inner {
  height: var(--titlebar-height);
  color:hsl(
      var(--accent-h),
      var(--base-s),
      calc(var(--accent-l) - 10%)
    )
}`

And for back\forward buttons just remove line 1497.

**Comment by mgmeyers** [comment]
Thanks @ze-kel! What OS are you on?

**Comment by ze-kel** [comment]
I'm on windows 10. Does it look different on a Mac?

**Comment by mgmeyers** [comment]
Yeah, the minimize\maximize\close button styles are set by the OS on a mac, so it makes sense that their styles are off on windows.

**Comment by mgmeyers** [comment]
@ze-kel I've made some updates to the titlebar. Let me know if the window controls are still pure white (they shouldn't be any more). Also I made the forward/back buttons visible only on hover to keep things declutterd:

![Dec-31-2020 11-44-36](https://user-images.githubusercontent.com/2694747/103423831-c8edc700-4b5d-11eb-85f8-b2c1c3e42685.gif)
