### ISSUE TITLE
Minimize vertical jumps on list selection

### ISSUE THREAD

**Issue by WhiteNoiseDev** [mgmeyers/obsidian-california-coast-theme#111]
This is obsidian with default theme
![Animation01](https://user-images.githubusercontent.com/3163647/148001165-039b0b13-9854-4c14-90cb-a3dcad6cc12e.gif)

This is California Coast
![Animation02](https://user-images.githubusercontent.com/3163647/148001187-6abad040-1a9c-4914-909e-f05dcba7e285.gif)

I think obsidian 0.13.17 introduced something to help minimize the vertical jumps on list selection. <https://forum.obsidian.md/t/obsidian-release-v0-13-17-insider-build/29522>

**Comment by mgmeyers** [comment]
Thanks @WhiteNoiseDev This should be fixed now in the latest version of the theme / obsidian. Let me know if you still have issues with it

**Comment by WhiteNoiseDev** [comment]
It works. Is it intended that the bullet points are black?
![image](https://user-images.githubusercontent.com/3163647/148666607-e74835b0-2f9f-427f-8b23-c2667ea3c613.png)

**Comment by mgmeyers** [comment]
@WhiteNoiseDev Ah, no, my bad. Just pushed a fix for this.

**Comment by WhiteNoiseDev** [comment]
I got fix! ♥👍
