### ISSUE TITLE
Consistent bold, italic, code coloring

### ISSUE THREAD

**Issue by epi-sam** [mgmeyers/obsidian-california-coast-theme#112]
Hello, new to Obsidian, trying some themes and this one seems really fantastic.  I normally work in editor mode, was wondering if it's possible to have bold, italic and code coloring consistent between editor and preview?  It's particularly nice to have a unique color for each in both places so the text type is visible.  

Anyway, great work!  Thank you.

edit: realized I was using the legacy editor w/o live preview (which I do prefer).  In any case, a way to edit the code font color would be lovely, if possible!

![image](https://user-images.githubusercontent.com/96550052/148290001-fd41e1b4-1aff-4a10-bebf-ab44f4bd5dab.png)
![image](https://user-images.githubusercontent.com/96550052/148290028-6e698223-4aa9-46f6-8972-287b5d098eea.png)

**Comment by mgmeyers** [comment]
@epi-sam Are the screenshots above from California Coast? It looks like you might be referencing a different theme.

**Comment by epi-sam** [comment]
Hi, yes they are.  Sorry for the late reply, been underwater at work recently.

I'm sorry I'm not up to speed on how to record an informative gif of myself, but here are some recent screenshots.  Different colors, same idea.

![image](https://user-images.githubusercontent.com/96550052/150657796-fa23bf85-e220-4265-ac38-b77060d1a06b.png)

![image](https://user-images.githubusercontent.com/96550052/150657803-34f85a56-07db-4f07-b0b2-53b350236da1.png)

![image](https://user-images.githubusercontent.com/96550052/150657814-57305c9b-bf94-4c8c-86cb-85bb058baa77.png)

![image](https://user-images.githubusercontent.com/96550052/150657827-4e84d05c-db2f-4ddc-8b9d-58a71e3a6a7f.png)

**Comment by mgmeyers** [comment]
Thanks for the clarification @epi-sam. I've made some updates so the colors are correctly picked up in the legacy editor

**Comment by epi-sam** [comment]
This is pretty awesome, thank you so much.

Is there any possibility to select the code formatted color.  Helps visibility especially with dark themes.

**Comment by mgmeyers** [comment]
@epi-sam I've added a setting for indented code color, but forcing a color on code blocks messes with syntax highlighting, so I've left that out.
