### ISSUE TITLE
Is it possible to have vertical line next to bullet points? 

### ISSUE THREAD

**Issue by ironhak** [mgmeyers/obsidian-california-coast-theme#114]
Here's what I mean:
![image](https://user-images.githubusercontent.com/62611612/149174053-52cce7bf-9cd4-451f-ba12-cb9877f7af70.png)
Thank's, and by the way this is an awesome theme.

**Comment by mgmeyers** [comment]
@ironhak Yes, I'd recommend install the Indentation Guides plugin. It'll give you these lines in any theme you use

**Comment by ironhak** [comment]
Hi thank's for your input. I tried the plugin and it works well. By the way I found this issue:
![image](https://user-images.githubusercontent.com/62611612/149293323-f98d5cf3-b794-42e2-b1b4-3e23a318df03.png)
Maybe you want to consider a fix or just implementing this natively on your amazing theme. 

Have a nice day and thank's.

**Comment by mgmeyers** [comment]
@ironhak That was a bug with the plugin. If you update the plugin it should now be fixed
