### ISSUE TITLE
brackets syntax highlighting

### ISSUE THREAD

**Issue by derekvan** [mgmeyers/obsidian-california-coast-theme#115]
This theme colors wikilinks (double brackets) blue, but it also colors text between single brackets in the same way. Could the coloring be made more sensitive to only highlight links instead of text between single brackets?
<img width="228" alt="Screen Shot 2022-01-24 at 8 54 24 AM" src="https://user-images.githubusercontent.com/890341/150795490-bfac648a-e946-4fa6-8462-13ed925c6619.png">

**Comment by mgmeyers** [comment]
Thanks @derekvan, this should be fixed now.
