### ISSUE TITLE
[BUG]When search inside note，it turned to blank note

### ISSUE THREAD

**Issue by Masktial** [mgmeyers/obsidian-california-coast-theme#116]
When I search inside note, it turned to blank note as below:
![image](https://user-images.githubusercontent.com/82996431/151112282-04cd24fa-bf4c-4739-a140-a2694c3630f4.png)

I closed all plugns, not fixed it.
Use the old editor，newest ob version.

Thanks.
Love your works.

**Comment by mgmeyers** [comment]
Thanks @Masktial this should be fixed now
