### ISSUE TITLE
File recovery snapshots window problem

### ISSUE THREAD

**Issue by CavalloneChen** [mgmeyers/obsidian-california-coast-theme#118]
california-coast version: 2.0.0
style-settings version: 0.4.9

In california-coast, the file recovery snapshots window is not properly shown:
![image](https://user-images.githubusercontent.com/28266566/153835737-7a43e21e-2e6b-4f28-9a04-3089fc46da26.png)

versus minimal theme
![image](https://user-images.githubusercontent.com/28266566/153835777-ef076930-c55e-4e66-b1d3-f24ad687dfcd.png)

**Comment by lakinchris** [comment]
seconding this!

**Comment by mgmeyers** [comment]
Apologies for the delay on this. It should be fixed now.

**Comment by lakinchris** [comment]
omg! yes it works. ty!
