### ISSUE TITLE
Different fonts for headings and main text body

### ISSUE THREAD

**Issue by dsent** [mgmeyers/obsidian-california-coast-theme#119]
I find it useful to have a font for headings that is different from the main text font.
This adds another dimension to #51 (which is a bit obsolete now with live preview).

Another excellent theme, Primary, implements this quite nicely with the help of your Style Settings plugin (btw, the settings are organized quite nicely there):
![image](https://user-images.githubusercontent.com/8774536/154019136-4c7041fd-2633-475c-8390-9c1ffbfafdad.png)

**Comment by mgmeyers** [comment]
Thanks @dsent I've added a setting to set the font for headings
