### ISSUE TITLE
Plugin pane checkbox display problem

### ISSUE THREAD

**Issue by HuangAdam** [mgmeyers/obsidian-california-coast-theme#120]
Plugin: [obsidian-plugin-todo](https://github.com/larslockefeer/obsidian-plugin-todo)
**Obsidian Origin Theme**:
![Quicker_20220319_013358](https://user-images.githubusercontent.com/46439030/159055773-b4811bdb-44dd-4702-836e-f89ac9c9ee90.png)

**California Coast Theme**:
![Quicker_20220319_013407](https://user-images.githubusercontent.com/46439030/159055933-1db8675a-eee5-4eed-9a45-d694f1bf3074.png)

**Comment by mgmeyers** [comment]
Thanks @HuangAdam this should be fixed now
