### ISSUE TITLE
Window can not be shown entirely or be scrolled down to its real bottom

### ISSUE THREAD

**Issue by DenryDu** [mgmeyers/obsidian-california-coast-theme#121]
![feedback1](https://user-images.githubusercontent.com/44111264/162578920-ee281e2e-3aab-4b5f-9fd8-2215f71a10ac.jpg)
![feedback2](https://user-images.githubusercontent.com/44111264/162578925-f0313499-923f-46e9-979e-c82351bf7c4f.jpg)

**Comment by mgmeyers** [comment]
@DenryDu I've fixed the issues with popover scrolling. What plugin are you using in the first screenshot?
