### ISSUE TITLE
Hover editor sizing not respected

### ISSUE THREAD

**Issue by derekvan** [mgmeyers/obsidian-california-coast-theme#123]
In the Hover Editor plugin settings, I set the hover pane to be 600x600. Works fine in the default theme. In California Coast, the content is constrained to a smaller area.
<img width="863" alt="Screen Shot 2022-05-01 at 1 25 00 PM" src="https://user-images.githubusercontent.com/890341/166157132-bf7afb72-6a42-4218-a039-cec6310286cc.png">

**Comment by mgmeyers** [comment]
Thanks @derekvan, this should be fixed now! Let me know if you run into any other issues with it
