### ISSUE TITLE
Right click menu is too transparent

### ISSUE THREAD

**Issue by ze-kel** [mgmeyers/obsidian-california-coast-theme#15]
Not sure how it looks on a mac but on windows it looks like this
![image](https://user-images.githubusercontent.com/63189390/103103657-990d6380-4633-11eb-888f-f00db4c4bb6a.png)

**Comment by mgmeyers** [comment]
Ah, thanks @ze-kel. It looks like this is related to the translucency plugin (turning it off fixes this). I'll investigate

**Comment by ze-kel** [comment]
I have transparency off though because it doesn't work on windows.
