### ISSUE TITLE
More options for customization

### ISSUE THREAD

**Issue by kangruixiang** [mgmeyers/obsidian-california-coast-theme#16]
Really love your theme. I think some more options for customization as next step would be line height and accent colors. Thank you. 

Edit: the other thing would be sidebar font. The default body font is quite large, but the font size for the right sidebar remain small.

**Comment by mgmeyers** [comment]
@kangruixiang I've updated the theme / settings plugin to support changing the line height and the accent color. I'll look into allowing changes to the UI font size, but that'll take more work due to some quirks with the icons.

**Comment by kangruixiang** [comment]
Thank you. That worked wonderfully well.
