### ISSUE TITLE
Vault title

### ISSUE THREAD

**Issue by ze-kel** [mgmeyers/obsidian-california-coast-theme#17]
By default obsidian has vault title name on top of file list. It's useful when you want to drag a note from a subfolder to a root directory.
![image](https://user-images.githubusercontent.com/63189390/103304847-b4ed7c80-4a1a-11eb-8e34-1c9779a196d4.png)
With the theme enabled it's gone and there is no way to move anything to root.

**Comment by mgmeyers** [comment]
@ze-kel I've added a little "drop zone" at the top of the list that should fix this.

![Dec-31-2020 12-16-12](https://user-images.githubusercontent.com/2694747/103424603-179d6000-4b62-11eb-8a47-ced62c5f8716.gif)
