### ISSUE TITLE
The cursor height is not consistant and nice.

### ISSUE THREAD

**Issue by lastingman** [mgmeyers/obsidian-california-coast-theme#18]
![image](https://user-images.githubusercontent.com/10057502/103432867-dbc9cf80-4c21-11eb-8e72-44a56809f543.png)
![image](https://user-images.githubusercontent.com/10057502/103432870-e1bfb080-4c21-11eb-8494-ea00e326f531.png)

BTW, thank you for the awesome theme.

**Comment by ze-kel** [comment]
#13
