### ISSUE TITLE
.side-dock-settings Padding

### ISSUE THREAD

**Issue by ze-kel** [mgmeyers/obsidian-california-coast-theme#3]
In cc-main line 745

.side-dock-settings {
  padding: 0;
}

This makes bottom buttons overlap 
![image](https://user-images.githubusercontent.com/63189390/102248130-e1c96c00-3f11-11eb-822e-42cf56f6abb2.png)

Can be fixed either by removing it altogether(not sure what's the purpose, doesn't seem to affect anything) or explicitly making the padding-bottom default 20px.

**Comment by mgmeyers** [comment]
Thanks for reporting this! I hide the app ribbon using the hider plugin, so it makes sense that I missed this. should be an easy fix.

**Comment by mgmeyers** [comment]
@ze-kel I've updated cc-main to support a non-hidden app ribbon. Feel free to open another issue if it still seems off to you!
