### ISSUE TITLE
Version history in Obsidian Sync shows as translucent, making it very hard to work with

### ISSUE THREAD

**Issue by mgmeyers** [mgmeyers/obsidian-california-coast-theme#39]
See: https://github.com/mgmeyers/obsidian-california-coast-settings/issues/2

**Comment by ConorMatthews** [comment]
Having the same issue

**Comment by mgmeyers** [comment]
I do not have access to Obsidian Sync and would love some help on this one.

**Comment by ConorMatthews** [comment]
I think you may still be able to access the version control window if you enable sync even without paying for it. Just shows as no historic versions.
I'm not much help otherwise, sorry.

**Comment by mgmeyers** [comment]
Thanks @ConorMatthews, that is helpful.

I've pushed a potential fix (added a background color to the modal). But someone with sync access will need to test it to confirm.

**Comment by ConorMatthews** [comment]
I'll give it a test once I can install the update as I have sync access.

**Comment by ConorMatthews** [comment]
Just checked it. It's all good!
Thanks so much @mgmeyers, love the theme.

**Comment by cashew90** [comment]
Sorry for not replying earlier.. it works, thank you for the great theme and the fix!
