### ISSUE TITLE
Make space between headings configurable 

### ISSUE THREAD

**Issue by dvcrn** [mgmeyers/obsidian-california-coast-theme#41]
Following markdown:

```
# Heading 1 
some test
# Heading 2

some text

### Some subheading

Some more text
```

Looks like this in preview:

<img width="1009" alt="Screen Shot 2021-01-19 at 17 22 48" src="https://user-images.githubusercontent.com/688326/105007138-f520a780-5a7a-11eb-92ca-de43c559150d.png">

The space between some of these headings is huge and makes the document harder to navigate/glance. It would be nice if this is configurable to make it a bit smaller, similar to how line-height is configurable

**Comment by mgmeyers** [comment]
Hey @dvcrn! Thanks for the suggestion.

One thing to note is that the padding sizes are relative to context and semantics—they come from http://matejlatin.github.io/Gutenberg/. So in your example you have two level 1 headings when in theory there should only be a single level 1 heading per page. 

Semantics don't really matter, though, for personal knowledge management, so I'll definitely take your advice make this more flexible and configurable.

**Comment by dvcrn** [comment]
That's a very good point, I didn't consider semantics

**Comment by iojw** [comment]
+1 for this. It would be great if the spacing in preview could match the spacing in edit mode more closely because the fonts and styles between both of these modes are already similar except for this change in spacing.

**Comment by janpeeters70** [comment]
I would love a feature to define the space between headers and body text in your theme too.
I noticed that Gutenberg calculates it's sizes. It would be great if your theme would have a setting to define the maximum H1 size and calculate respective smaller header sizes in steps down to the size of the body font size (for h5 and h6 cursive). I think with these additions someone could make the preview totally to his/her liking. 
It would be great if the editor and preview looked almost the same in their representation of the note.

**Comment by mgmeyers** [comment]
Hey all, I've made the heading sizes and margins configurable via the theme plugin. Please update the theme and the plugin, and let me know if your use case has been covered!
