### ISSUE TITLE
Folding doesn't happen in editor mode. Please solve it. The theme is beautiful

### ISSUE THREAD

**Issue by jayprog884** [mgmeyers/obsidian-california-coast-theme#42]

**Comment by mgmeyers** [comment]
@jayprog884 Can you update your theme and confirm that this is still an issue? I fixed a similar issue the other day which may have fixed this.

**Comment by mgmeyers** [comment]
Closing this out because I believe the issue has been fixed. Feel free to open a new issue if this is not the case
