### ISSUE TITLE
Line height issues with lists

### ISSUE THREAD

**Issue by kangruixiang** [mgmeyers/obsidian-california-coast-theme#44]
Hi, I'm having some issues with line height when using lists. My current body line height is set to 1.5. Seems the line height between sub list and the next list is smaller. For example, line height between "associated" and "If 21-hydroxylase" is less compared to the others:

![](https://i.imgur.com/GimktFO.png)

**Comment by mgmeyers** [comment]
Hi @kangruixiang,

Did you by chance change obsidian's tab size?

<img width="634" alt="Screen Shot 2021-02-08 at 12 06 07 PM" src="https://user-images.githubusercontent.com/2694747/107275042-18999b00-6a06-11eb-84db-eec31186de5d.png">

There's an issue with obsidian where lists will only be detected when the tab size is set to 4.

Tab size 4 (notice that each list item begins with a bullet):
<img width="172" alt="Screen Shot 2021-02-08 at 12 04 48 PM" src="https://user-images.githubusercontent.com/2694747/107275126-30711f00-6a06-11eb-97c6-865b5cce5732.png">

Tab size 6 (notice the dashes where the lines aren't detected as list items):
<img width="206" alt="Screen Shot 2021-02-08 at 12 05 39 PM" src="https://user-images.githubusercontent.com/2694747/107275157-39fa8700-6a06-11eb-8225-02fc3efe6f93.png">


Looking at your screenshot, it looks like the tab size may be too small to be recognized by obsidian.

**Comment by mgmeyers** [comment]
Another thing to check is if you're using spaces or tabs:

<img width="635" alt="Screen Shot 2021-02-08 at 12 12 44 PM" src="https://user-images.githubusercontent.com/2694747/107275775-0835f000-6a07-11eb-942b-89fae0c0a135.png">

This setting will also affect if/when lists are detected by obsidian.

**Comment by kangruixiang** [comment]
Oh ok that fixed it. Thank you so much. I thought the dash is just a feature for sublists.
