### ISSUE TITLE
Dark mode highlight is black

### ISSUE THREAD

**Issue by mgmeyers** [mgmeyers/obsidian-california-coast-theme#47]
Should use accent color

**Comment by macintacos** [comment]
Was just about to open this same issue here - when highlighting text in the dark mode it's very difficult to determine what you've actually highlighted.

**Comment by mgmeyers** [comment]
So, I'm not sure what's going on here. It seems to only happen sporadically. If anyone can find a consistent way to reproduce this, please let me know.
