### ISSUE TITLE
Calculated header sizes from max H1 size

### ISSUE THREAD

**Issue by janpeeters70** [mgmeyers/obsidian-california-coast-theme#50]
I noticed that Gutenberg calculates it's header sizes. It would be great if your theme would have a setting to define the maximum H1 size and calculate respective smaller header sizes in steps down to the size of the body font size. 
With these additions someone could make the preview totally to his/her liking. 
It would also be great if the editor and preview looked almost the same in their representation of the note.

**Comment by perfidopelato** [comment]
I second this: I like to use very small fonts and currently there’s a huge difference between the body text and the header.

**Comment by janpeeters70** [comment]
That's my preference too!

**Comment by orphee-celui-qui-ne-sait-rien** [comment]
me too! it's very uncomfortable to have a small font with gigantic headers, specially since I have a small screen :/

**Comment by mgmeyers** [comment]
Hey all, I've made the heading sizes and margins configurable via the theme plugin. Please update the theme and the plugin, and let me know if your use case has been covered!

**Comment by janpeeters70** [comment]
Hi @mgmeyers, thanks a lot for this addition. really appreciated! 
I don't get it to work though. I have set different sizes but I see any changes in neither the editor nor the preview. I might missing something but even with all other plugins and css tweaks turned off it doesn't change sizes. Do you know what could be wrong?

**Comment by mgmeyers** [comment]
@janpeeters70 Did you reinstall the theme CSS in addition to updating the plugin?

**Comment by janpeeters70** [comment]
Thanks @mgmeyers I forgot to update the theme. Thought there would be some update mechanism in place in Obisidian. All working great now. Thank you very much for implementing this!
