### ISSUE TITLE
Optional bullet rappresentation of dashes in editor

### ISSUE THREAD

**Issue by perfidopelato** [mgmeyers/obsidian-california-coast-theme#52]
Currently in a bullet list the dash is replaced by a bullet in both editor and preview.

I’d like to be able to keep the dash as it is in the editor.

**Comment by perfidopelato** [comment]
Currently in a bullet list the dash is replaced by a bullet in both editor and preview. 

I’d like to be able to keep the dash as it is in the editor.

**Comment by mgmeyers** [comment]
@perfidopelato This is finally possible after the latest update!

I've added a setting to Style Settings to toggle list bullets in the editor:

<img width="722" alt="Screen Shot 2021-07-16 at 10 48 50 AM" src="https://user-images.githubusercontent.com/2694747/125988652-7a35a60f-3c8c-470b-a345-da46c26bd5dd.png">
