### ISSUE TITLE
Almost No Margin/Padding between Sidebar & Preview Pane

### ISSUE THREAD

**Issue by shalintj** [mgmeyers/obsidian-california-coast-theme#53]
The margins look quite strange in the preview mode. 

There is practically no margin/padding between the sidebar and preview pane

Editor:
![editor](https://user-images.githubusercontent.com/8264186/109312662-518e9800-786d-11eb-803b-d3246624be09.png)

Preview:
![preview](https://user-images.githubusercontent.com/8264186/109312691-56ebe280-786d-11eb-8bcf-8b0c26a4af31.png)

How do I fix this?

**Comment by orphee-celui-qui-ne-sait-rien** [comment]
# Heres a solution to this, just use this snippets in your vault

```
/* Done by SlRvb#3223 from the Obsidian discord */

.workspace .markdown-preview-view{
      padding: 20px 30px 50px 30px;
}
```

```
/* Done by SlRvb#3223 from the Obsidian discord */

.CodeMirror-scroll {
    margin: 0;
    padding: 0;
}
```

**Comment by mgmeyers** [comment]
@shalintj & @orphee-celui-qui-ne-sait-rien I just pushed a fix for this. Pull down the latest theme and let me know if you still have issues.
