### ISSUE TITLE
Quotes (and probably other stuff) becomes an absurdly long length when opened from a sidebar on smaller widths

### ISSUE THREAD

**Issue by qt-dork** [mgmeyers/obsidian-california-coast-theme#54]
It's possible that this is just an issue with obsidian in general? I didn't run into this issue with the default theme, but the default theme also puts block quotes in blocks. Here's a gif showing how to do it, the line (and by that logic, the content below it) doesn't change length when opened in a state that pushes the content down, like from a sidebar. This issue doesn't arise if the window is large enough that the sidebar doesn't push the content down. 

Here is a gif showing you how to replicate it:
![CleanShot 2021-03-01 at 00 23 36](https://user-images.githubusercontent.com/38471874/109471154-35cdf200-7a25-11eb-84f3-0890622e1cc0.gif)

**Comment by mgmeyers** [comment]
Hey @qt-dork 

I had a look, and this does seem to be an issue on Obsidian's end, and I can reproduce it with the default theme. 

When the preview window is first loaded, Obsidian adds a minimum height to the embedded block, probably so it doesn't scroll. They don't seem to be reducing the height when the preview width gets wider, though, causing the issue you see.

Going to close this out, thanks for reporting!
