### ISSUE TITLE
Colour settings for body text, headings and other main elements

### ISSUE THREAD

**Issue by janpeeters70** [mgmeyers/obsidian-california-coast-theme#56]
I was thinking that what if CC would include colour settings for headings and body text or even other elements like links, bold etc. I know you can do it with CSS and I don't know if this would be loads of work but it would make CC the most easily tweakable theme for Obsidian I guess.

**Comment by mgmeyers** [comment]
Hey @janpeeters70 ! I know this isn't quite what you asked, but I added CSS variables to control heading colors. I'm hesitant to add too many more settings until I can figure out how to make them more manageable to navigate.

Using the new [Style Settings](https://github.com/mgmeyers/obsidian-style-settings) plugin, you can create a CSS snippet that will allow you to tweak these variables in the plugin settings:

```CSS
/* @settings

name: Heading Colors
id: heading-colors
settings:
    - 
        id: h1-color
        title: H1 Color
        type: variable-color
        format: hex
        default: '#000000'
    - 
        id: h2-color
        title: H2 Color
        type: variable-color
        format: hex
        default: '#000000'

*/
```

In fact, any CSS variable used by the theme can be overridden in this way. Here are all the variables the theme uses:

https://github.com/mgmeyers/obsidian-california-coast-theme/blob/main/src/070-headers.css#L46-L51
https://github.com/mgmeyers/obsidian-california-coast-theme/blob/main/src/010-main.css#L1-L205

If there's something you'd like to tweak via a variable, let me know and I'll see if I can wire it up!

**Comment by janpeeters70** [comment]
Hi @mgmeyers I can understand your hesitation really well. It might create a forest of options that are not viable for everyone. Your Style Settings plugin looks incredible. 
I've tinkered around with CSS the past week and got some things to my liking by using the colour section from the Cybertron theme and using that to control the colours in your theme, but this makes the process a lot more easy. 

Thanks again, also for taking the time for your extensive reply. Greatly appreciated. 

Best, Jan

**Comment by janpeeters70** [comment]
Hi @mgmeyers I've installed your plugins Style Settings and Contextual Typography and created a CSS snippet with the below code and I've activated the snippet.
```
/* @settings

name: Heading Colors
id: heading-colors
settings:
	- 
		id: h1-color
		title: H1 Color
		type: variable-themed-color
		format: hex
		default-light: '#000000'
		default-dark: '#FFFFFF'
	- 
		id: h2-color
		title: H2 Color
		type: variable-themed-color
		format: hex
		default-light: '#000000'
		default-dark: '#FFFFFF'
	- 
		id: h3-color
		title: H3 Color
		type: variable-themed-color
		format: hex
		default-light: '#000000'
		default-dark: '#FFFFFF'
	- 
		id: h4-color
		title: H4 Color
		type: variable-themed-color
		format: hex
		default-light: '#000000'
		default-dark: '#FFFFFF'
*/
```
I've refreshed the snippets sections in Obsidian settings and force-reloaded Obsidian but I don't seem to be able to make the new settings show up in your Style Settings plugin. What could I be doing wrong? Thanks in advance.

**Comment by mgmeyers** [comment]
Ah, thanks @janpeeters70! It turns out there was a minor bug when parsing YAML with tabs instead of spaces. Try updating the Style Settings plugin and trying again!

**Comment by janpeeters70** [comment]
Hi @mgmeyers Now it works like a charm. Thanks for fixing it so quickly. Researching the possibilities of your plugin I realize that you've made a huge contribution to the Obsidian theming and customization community. Hopefully developers will join in to help you with improvements.

**Comment by janpeeters70** [comment]
> If there's something you'd like to tweak via a variable, let me know and I'll see if I can wire it up!

I would love to be able to have settings for:
**Bold**: font-weight and color
_Emphasis_: color
File-tree: font-size and line-height (but I don't know if the distance between file-tree items is done via padding or line-height)

Let me know if my requests require too much of your time. I can also achieve it with CSS of course.

Thanks, Jan

**Comment by mgmeyers** [comment]
@janpeeters70 I should get notifications on all activity in this git repo!

Also, I've added a few more variables per your request:

```
--strong-weight: var(--bold-weight);
--strong-color: inherit;
--em-color: inherit;
```

**Comment by janpeeters70** [comment]
Thank you very much!

**Comment by janpeeters70** [comment]
Hi Matthew

I was tinkering some more with the colors of your theme via the Style Settings plugin. 
I noticed that the Accent color is used for the accents in the UI but also for all internal, external links and tags. 
I love to have my links in a dark magenta color but for the accents in the UI a shade of blue does a better job. 
Is there a way to uncouple them so that I can define a separate color for all sorts of 'links' and the UI accents?

_As always if my requests take too much of your time, just say so, no offense taken. I'm grateful for all your work._

Best, Jan
