### ISSUE TITLE
Code block style bug

### ISSUE THREAD

**Issue by izuolan** [mgmeyers/obsidian-california-coast-theme#57]
https://github.com/mgmeyers/obsidian-california-coast-theme/blob/main/obsidian.css#L4589

```
.markdown-preview-view code {
  color: var(--text-normal);
  font-size: 0.9em;
  margin: -2px 0;  /* This margin causes a vertical scrollbar in the code block, but in reality this scrollbar should not appear. I think this line style is unnecessary. */
}
```

before:

![before.png](https://i.loli.net/2021/03/26/Y7E2okB6bDli5Wy.png)

after:

![after.png](https://i.loli.net/2021/03/26/KroD5dgpQF6WHux.png)

**Comment by mgmeyers** [comment]
This should be fixed in the latest release. Please update the theme and install the new Style Settings plugin (California Coast Theme Settings plugin is now deprecated)
