### ISSUE TITLE
Accent color value

### ISSUE THREAD

**Issue by kangruixiang** [mgmeyers/obsidian-california-coast-theme#58]
I think to make the color choices complete, the accent color option should have hue, saturation, and value sliders. The addition of value slider would really change the lightness or darkness of the color.

**Comment by mgmeyers** [comment]
@kangruixiang You should now have more control over the accent color. Please update the theme and install the new Style Settings plugin (California Coast Theme Settings plugin is now deprecated)

**Comment by kangruixiang** [comment]
The new style setting plugin page opens up to a blank page, even after restarting the app.

**Comment by mgmeyers** [comment]
@kangruixiang Try downloading the theme again and updating the Style Settings plugin. I've fixed some bugs today they may fix your issue. If not, let me know.

**Comment by kangruixiang** [comment]
That fixed it. Thank you.
