### ISSUE TITLE
Text spacing too large in preview window?

### ISSUE THREAD

**Issue by spencernewton** [mgmeyers/obsidian-california-coast-theme#59]
I was wondering if there was a setting we could change for the markdown preview window; when setting up multiple headers, there is just a gigantic space before each header that is not present in any other theme I've used and makes the file too spaced out looking. Not sure if this is an issue for everyone but it seems to be present in screenshots so I would think its the theme itself.

**Comment by mgmeyers** [comment]
@spencernewton This is configurable! Please update the theme and install the new Style Settings plugin (California Coast Theme Settings plugin is now deprecated). There you'll see settings for the margin of each level of heading:

<img width="906" alt="Screen Shot 2021-04-04 at 1 44 05 PM" src="https://user-images.githubusercontent.com/2694747/113521048-ddba6c00-954b-11eb-9b93-1b8588767f8f.png">
