### ISSUE TITLE
Can not scroll in page preview

### ISSUE THREAD

**Issue by Clivusistheseatofthesoul** [mgmeyers/obsidian-california-coast-theme#61]
The page preview is stuck at the top of each page. I can't seem to scroll nor do I see the scroll bar.

**Comment by mgmeyers** [comment]
Hi @Clivusistheseatofthesoul can you:

- Make sure the California Coast settings plugin is uninstalled
- Download the theme again from the community themes list
- Ensure the Style Settings plugin is downloaded and up to date

Let me know if updating everything doesn't help!

**Comment by gabros20** [comment]
Hey @Clivusistheseatofthesoul! Try to turn OFF the "Seamless Embed" feature in Style Settings plugin. I found that turning this ON might causing the reported issue.

**Comment by mgmeyers** [comment]
Ah, thanks for the tip @gabros20! I see the issue now. I've made some updates to the theme that should fix this. Try downloading the theme and trying again!

**Comment by gabros20** [comment]
Tested with a new vault and clean setup, it seems to be fixed now. Scroll works great with "Seamless Embed" feature turned ON. Thanks for the quick Fix @mgmeyers! 👏 

![Kapture 2021-04-09 at 15 45 12](https://user-images.githubusercontent.com/49348865/114189855-f1e6da80-994a-11eb-95a7-37bc2df4ae9f.gif)
