### ISSUE TITLE
Links bleeding through on mobile

### ISSUE THREAD

**Issue by ddetton** [mgmeyers/obsidian-california-coast-theme#62]
Using CC theme with Style Settings plugin on Windows 10 desktop and iOS mobile.  On mobile, when I have a file open in Andy’s mode then open the file explorer, any link that was visible in the file bleeds through to the file explorer.  Not sure whose problem it is.   I have attached a few screen shots. 
![14A188BC-9185-4710-B864-D87F4287E503](https://user-images.githubusercontent.com/3335359/113615452-be354900-9608-11eb-85ba-8a99288c7c77.png)
![C94C167A-061E-42FE-89BC-CDE136B938BF](https://user-images.githubusercontent.com/3335359/113615457-bfff0c80-9608-11eb-9f07-60bafe8d4c16.png)

**Comment by mgmeyers** [comment]
Thanks @ddetton! I think I figured out what was causing this. Try downloading the theme again and see if the issue persists.

**Comment by ddetton** [comment]
Tested on iPadOS and iOS and problem solved on both.  This issue can be closed now.
