### ISSUE TITLE
Lots of space between objects

### ISSUE THREAD

**Issue by ddetton** [mgmeyers/obsidian-california-coast-theme#63]
This may just be a trait of this css but there seems to be quite a lot of space between lines on the CC theme.  If there is a way to tighten this up more like the cybertron theme, I would like CC a lot better.  This is the same file.  First is CC and second is cybertron theme.

![image](https://user-images.githubusercontent.com/3335359/113793762-e652a400-96fd-11eb-8dc4-82f32941b577.png)

![image](https://user-images.githubusercontent.com/3335359/113793772-ece11b80-96fd-11eb-9772-1a2aacf6fb66.png)

**Comment by mgmeyers** [comment]
Yeah, what you're seeing is the margins of the headings, and these margins can be adjusted for each heading using the Style Settings plugin:

<img width="1056" alt="Screen Shot 2021-04-06 at 5 45 23 PM" src="https://user-images.githubusercontent.com/2694747/113794756-2581f480-9700-11eb-82b3-958826df670a.png">
