### ISSUE TITLE
Section highlight from clicked link

### ISSUE THREAD

**Issue by lkhphuc** [mgmeyers/obsidian-california-coast-theme#64]
If I clicked on an embed heading or section link (`[[today#journal]]`), the `today` note will be open and the `#journal` heading will be displayed with a square surrounding each word like this.
![image](https://user-images.githubusercontent.com/12573521/113867895-fbcfd880-97a6-11eb-90fe-6c7f18f4ab4b.png)

**Comment by mgmeyers** [comment]
Thanks @lkhphuc! I've reverted back to the default highlights to prevent this from happening. You'll now see something more like:

<img width="356" alt="Screen Shot 2021-04-08 at 6 49 41 PM" src="https://user-images.githubusercontent.com/2694747/114117278-34e97500-989b-11eb-87d8-8cf6c6a5cc03.png">

**Comment by lkhphuc** [comment]
Thanks, it worked perfect now.
