### ISSUE TITLE
Toolbar buttons not aligned on mobile (iOS)

### ISSUE THREAD

**Issue by astrodad** [mgmeyers/obsidian-california-coast-theme#66]
Hi,

Just started to use this theme and the Obsidian mobile beta. When on my iPhone 12 Plus, running iOS 14.5 beta 6, I see this behavior with the left side toolbar buttons. 

![F4BAF9FC-D767-4742-AB85-BA94DD478CEF](https://user-images.githubusercontent.com/1663239/114484394-20c5b080-9bd8-11eb-9122-0ba17e689823.png)
![CFEB5B67-8811-4F2F-BD84-128753BDA150](https://user-images.githubusercontent.com/1663239/114484397-215e4700-9bd8-11eb-900b-c7299511d2fc.png)

**Comment by janpeeters70** [comment]
I'm having the same issue and noticed some other things that could be improved on mobile like the width of the text, there's currently a lot of whitespace around the text in preview mode and there is a scrollbar horizontally in editor mode. 
But the most important question is if you are already on the mobile client @mgmeyers and able to check it?

**Comment by mgmeyers** [comment]
Hey All, I've made some significant updates to support mobile. This should be fixed now. Let me know if you still have issues.
