### ISSUE TITLE
Bug in outline

### ISSUE THREAD

**Issue by iris2jane** [mgmeyers/obsidian-california-coast-theme#68]
When a switch of the Outliner plugin is turned on, the outline style of California Coast theme seems to be a little abnormal (compared with the native theme)

![image](https://user-images.githubusercontent.com/36763930/115414506-aaa0f980-a228-11eb-813b-59bb50241972.png)

![image](https://user-images.githubusercontent.com/36763930/115414234-70cff300-a228-11eb-90e9-80f9503158bf.png)

**Comment by mgmeyers** [comment]
@iris2jane Yes, this directly conflicts with the bullets in California Coast. I recommend keeping the setting turned off when using outliner with this theme, but is there a reason you would like to use the outliner styles instead?
