### ISSUE TITLE
Problem with the management of Emoji in preview mode using Emoji Toolbar plugin

### ISSUE THREAD

**Issue by healBvdb** [mgmeyers/obsidian-california-coast-theme#70]
I am using Emoji Toolbar plugin to add a bit of color to my notes.
It seems that they are not correctly managed in preview mode there is a line feed before the icon which give strange outputs, specially when I’m using it inside a tag (#emoji-icon)

![image](https://user-images.githubusercontent.com/51165870/116373541-bb93d100-a80d-11eb-88f5-fd203ee830e5.png)
![image](https://user-images.githubusercontent.com/51165870/116373611-cc444700-a80d-11eb-8e45-1301311f1e11.png)

or

![image](https://user-images.githubusercontent.com/51165870/116373789-f85fc800-a80d-11eb-9995-3045a810b6f8.png)
![image](https://user-images.githubusercontent.com/51165870/116373867-0f061f00-a80e-11eb-80d7-c88241b57a74.png)

**Comment by mgmeyers** [comment]
Thanks @healBvdb! This should be fixed now. Try downloading the theme again.

**Comment by healBvdb** [comment]
Yes… Tested and that’s solved.
Thank you @mgmeyers
