### ISSUE TITLE
Cursor too big

### ISSUE THREAD

**Issue by CavalloneChen** [mgmeyers/obsidian-california-coast-theme#71]
The cursor size of this theme is so big. A smaller one may be more good-looking.

**Comment by mgmeyers** [comment]
@CavalloneChen the height of the cursor is determined by the line height CSS property. This is a limitation of the obsidian editor. If you decrease the "Body line height" with the Style Settings plugin, it will decrease the size of the cursor, but it will also have an effect on the look of the text.

<img width="734" alt="Screen Shot 2021-05-01 at 9 29 24 AM" src="https://user-images.githubusercontent.com/2694747/116788661-ba59e280-aa5f-11eb-8b26-66498a9921b9.png">

**Comment by CavalloneChen** [comment]
> @CavalloneChen the height of the cursor is determined by the line height CSS property. This is a limitation of the obsidian editor. If you decrease the "Body line height" with the Style Settings plugin, it will decrease the size of the cursor, but it will also have an effect on the look of the text.
> 
> 
> 
> <img width="734" alt="Screen Shot 2021-05-01 at 9 29 24 AM" src="https://user-images.githubusercontent.com/2694747/116788661-ba59e280-aa5f-11eb-8b26-66498a9921b9.png">
> 
> 

Got it, thanks for the advice 😁
