### ISSUE TITLE
Obsidian TODO | Text-based GTD plugin gets too small checkboxes

### ISSUE THREAD

**Issue by janpeeters70** [mgmeyers/obsidian-california-coast-theme#72]
I was checking out the Obsidian To-do | Text-based GTD plugin (very promising) and I noticed that in CC it gets too small checkboxes. See screenshots. I deactivated all plugins and custom code, but it stayed the same, so I guess it's something in the CC CSS. If you have the time I would appreciate it you could have a look at it.

This is how it looks like in default Obsidian Theme.
<img width="225" alt="Screencapture 2021-04-30 at 14 10 24@2x" src="https://user-images.githubusercontent.com/4502360/116792405-b14d2d80-aac0-11eb-8ed9-9f6fce16d4e1.png">
And this is how it looks like in CC
<img width="225" alt="Screencapture 2021-04-30 at 14 15 54@2x" src="https://user-images.githubusercontent.com/4502360/116792426-cb870b80-aac0-11eb-99a8-7a0e874723df.png">

https://github.com/larslockefeer/obsidian-plugin-todo

**Comment by mgmeyers** [comment]
Thanks @janpeeters70. Try it now, should be fixed.

**Comment by janpeeters70** [comment]
Yes that did it. Thanks.
