### ISSUE TITLE
Is it possible to include such an option so that images can be displayed left-centre-right

### ISSUE THREAD

**Issue by zhl111** [mgmeyers/obsidian-california-coast-theme#76]
![image](https://user-images.githubusercontent.com/29135984/117025721-bcf15c00-ad2d-11eb-84ab-44c8b7dc0e5d.png)

**Comment by mgmeyers** [comment]
@zhl111 I've added support for @SlRvb's image positions: https://github.com/SlRvb/Obsidian--ITS-Theme/blob/main/Guide/Image-Positions.md
