### ISSUE TITLE
Soft-Wrapping Code Blocks

### ISSUE THREAD

**Issue by ChristinWhite** [mgmeyers/obsidian-california-coast-theme#77]
I absolutely love California Coast, it feels so much more at home on macOS than any other theme. It's so polished, it really elevates Obsidian for me and coming from Bear, polish is the one thing I've been missing!

That said, I do have one request, i'd really love to not have to scroll side to side for code blocks to see longer rows, I'd love to have an option to soft-wrap them if possible.

**Comment by mgmeyers** [comment]
@ChristinWhite I've added a style setting for this! Let me know if you have any issues with it.

**Comment by ChristinWhite** [comment]
This is fantastic @mgmeyers, thank you so much!
