### ISSUE TITLE
Column lines in table

### ISSUE THREAD

**Issue by zoebjamal** [mgmeyers/obsidian-california-coast-theme#78]
Hi! First of all I think this is an awesome theme thank you so much for creating it! I wanted to ask if there was any way to get vertical column lines in tables. Attached are some screenshots.

California coast - no vertical column bars here
![Screen Shot 2021-05-07 at 6 09 17 PM](https://user-images.githubusercontent.com/62960617/117450830-60758300-af5f-11eb-8e92-d6c445bfbd24.png)

Other theme - vertical column bars present
![Screen Shot 2021-05-07 at 6 08 42 PM](https://user-images.githubusercontent.com/62960617/117450839-62d7dd00-af5f-11eb-9559-3e75ab83d63b.png)

**Comment by mgmeyers** [comment]
@zoebjamal I've added a style setting for this! Let me know if you have any issues with it.
