### ISSUE TITLE
Window border radius is incorrect for macOS

### ISSUE THREAD

**Issue by kristofferR** [mgmeyers/obsidian-california-coast-theme#80]
The border radius for the window corners of this theme is slightly incorrect on macOS Big Sur, leading to the Obsidian window being visible behind other windows with the exact same size.

Here's an example. The Finder window has exactly the same size and postion as the Obisidan window below.
<img width="731" alt="2021-05-21 kl  00 03 59" src="https://user-images.githubusercontent.com/481270/119054919-b9660200-b9c8-11eb-846c-f80c59ac4e73.png">

I found some information about the proper border radius here:
https://apple.stackexchange.com/questions/399414/what-is-the-radius-of-the-windows-on-bigsur

**Comment by mgmeyers** [comment]
Thanks @kristofferR, unfortunately this is something defined by electron, and not the theme. Are you on the latest version of the obsidian installer? The borders should match in the latest version of electron.

Here's finder in front of obsidian, for example: 

<img width="1010" alt="Screen Shot 2021-05-20 at 3 19 33 PM" src="https://user-images.githubusercontent.com/2694747/119056017-d70e7980-b97e-11eb-88cd-c2e0a9679452.png">

<img width="644" alt="Screen Shot 2021-05-20 at 3 20 58 PM" src="https://user-images.githubusercontent.com/2694747/119056159-0fae5300-b97f-11eb-94bc-4368a3c13a31.png">

**Comment by kristofferR** [comment]
Yeah, I used v0.12.3, but apparently an outdated version of v0.12.3 with old Electron. 

[Apparently](https://forum.obsidian.md/t/obsidian-release-v0-12-3/17957/2) you need to manually update Obsidian to get it fully updated. Border radius is correct now ;)
