### ISSUE TITLE
Arrow Symbol

### ISSUE THREAD

**Issue by bySandboxer** [mgmeyers/obsidian-california-coast-theme#84]
Thank you for this theme. It is absolutely beautiful.

I just noticed that there seems to be no recognition of the arrow symbol. Other themes detect '->' or '-->' and complete it to, for example: '→'.

**Comment by mgmeyers** [comment]
@bySandboxer this actually has more to do with the font. The default obsidian font `Inter` uses ligatures like the arrows you speak of. You can use the style settings plugin to change the editor font. Another option is to use the smart typography plugin which will actually convert `->` to a UTF8 arrow character.
