### ISSUE TITLE
Make heading-hash move the gutter to the left

### ISSUE THREAD

**Issue by tim-hilde** [mgmeyers/obsidian-california-coast-theme#87]
When toggling the new "Flush Headings" setting, the hashes interfere with the gutter, esp. with the folding arrows. Moving the hashes either into the gutter or the gutter to the left would solve this problem.

**Comment by mgmeyers** [comment]
@tim-hilde This is a known conflict between folding headers and the "Flush Headings" setting. Unfortunately, there really isn't a good workaround for this other than disabling one of these settings. Moving the gutter or hashes any more than they have been causes other issues.

Now that obsidian mobile is public, obsidian's WYSIWYG editor shouldn't be too far off. Once that's in, a lot of this won't be an issue.
