### ISSUE TITLE
Translucency Issues on Windows

### ISSUE THREAD

**Issue by phibr0** [mgmeyers/obsidian-california-coast-theme#89]
In Dark Mode the Header has a slightly different color (or isn't as translucent):

![image](https://user-images.githubusercontent.com/59741989/126895157-9f3b368b-5926-4042-be09-f0d2dd8668d2.png)

In Light Mode the Header doesn't change its color at all, looks like its still in Dark Mode:

![image](https://user-images.githubusercontent.com/59741989/126895172-d0a31f2c-01b4-472d-9c2b-2c5e561d94f4.png)

**Comment by mgmeyers** [comment]
@phibr0 This should be fixed now, can you confirm?

**Comment by phibr0** [comment]
Yes! Working fine again in both Light and Dark Mode
