### ISSUE TITLE
Hidden Settings - Color

### ISSUE THREAD

**Issue by Moenupa** [mgmeyers/obsidian-california-coast-theme#90]
In the Hidden settings - colors, there is a duplicate `--h5-color` at line 6803. I wonder whether it should be `--h6-color`.
```  
  /* Hidden settings */

  --h1-color: var(--text-normal);
  --h2-color: var(--text-normal);
  --h3-color: var(--text-normal);
  --h4-color: var(--text-normal);
  --h5-color: var(--text-normal);
  --h5-color: var(--text-normal); /* should be "6" not "5" */
```

Also, I would like to mention what possibly seems to be a bug about the exact same thing.

When modifying it with the existed css var `--color-rgb` (e.g. `--red-rgb`), it does not work.

```
  /* this will not work, if by default, being at line 6803 */
  --h1-color: rgba(var(--red-rgb), 0.9);
```

But if migrate the same to *line~=500*, within the `.theme-light {...}` and `.theme-dark {...}` definition blocks, it will be working again.

I think the main problem is that *line6803* falls through and fails to get the color vars in `.theme-light {...}` and `.theme-dark {...}`.

The solution might be any of:
- migrate to var definition blocks at the very start (*line~500*), the same as what I did
- use something like `.theme-light {...}` and `:not(.theme-light) {...}` to prevent fall-through (which I do not think is good practice)

**Comment by mgmeyers** [comment]
@Moenupa I've added Style Settings to allow you to adjust these colors:

<img width="759" alt="Screen Shot 2021-12-30 at 11 41 37 AM" src="https://user-images.githubusercontent.com/2694747/147783248-2459e591-f9e5-4144-ae8f-71d7d7cca6be.png">

Let me know if these work for you.
