### ISSUE TITLE
Graphic Anomalies on W11

### ISSUE THREAD

**Issue by anobongjimwel** [mgmeyers/obsidian-california-coast-theme#91]
- When maximizing while having the setting "Translucent window" enabled with light or dark mode, the window animates with color purple on whole window for some reason (Window's accent color maybe).
- Light mode with "Translucent window" on on Windows, doesn't activate acrylic design. Only applicable on title bar that is in dark mode

**Comment by xidsyed** [comment]
Window animation purple color expansion effect has nothing to do with the theme but windows 11, or obsidian itself, ,happens with all themes

**Comment by xidsyed** [comment]
![image](https://user-images.githubusercontent.com/26184016/164965405-3d6e1a48-a787-4142-825e-c04a5005fa8d.png)
Light mode with translucency works for me 🤷

**Comment by mgmeyers** [comment]
Yes, as xidsyed said, this is an issue with obsidian. Though it may have been fixed. I'd recommend reinstalling obsidian to get the latest electron version. It has much better support for transparency
