### ISSUE TITLE
Body Font Size doesn't have any effect

### ISSUE THREAD

**Issue by reisub0** [mgmeyers/obsidian-california-coast-theme#92]
Setting the body font size setting from the Style settings plugin doesn't seem to have any effect to change the size.

Is there something I'm missing?

**Comment by mgmeyers** [comment]
Ah, apologies for that. This is actually an old setting that isn't used any more. I'll removed it from the style settings config. 

Obsidian has a built in setting now for controlling font size:
<img width="1006" alt="Screen Shot 2021-08-02 at 9 46 56 AM" src="https://user-images.githubusercontent.com/2694747/127896104-f24d49a5-b7f2-40de-aea2-6ae3bfb47063.png">
