### ISSUE TITLE
[BUG] In numbered lists with checkboxes, the checkbox hides the numbers

### ISSUE THREAD

**Issue by rubslopes** [mgmeyers/obsidian-california-coast-theme#94]
Here's a screenshot:
<img width="843" alt="Captura de Tela 2021-08-14 às 18 03 33" src="https://user-images.githubusercontent.com/29660599/129459971-8986610d-589c-478e-9370-40c428a91f97.png">

I manage to solve this problem by simply commenting this part of the css file:

```
.markdown-preview-view .task-list-item-checkbox {
  width: 0.866em;
  height: 0.866em;
  position: relative;
  line-height: 0;
  /*margin-left: -1.1em;*/
  margin-right: 6px;
  filter: none;

  margin-bottom: 0;
  top: 2px;
}
```

I hope this does not break anything.

**Comment by mgmeyers** [comment]
Thanks for the bug report! This should be fixed now.
