### ISSUE TITLE
The background of the previewed page disappears when hovering

### ISSUE THREAD

**Issue by KElee01** [mgmeyers/obsidian-california-coast-theme#95]
When I was previewing a page that was not created, the background of the previewed page disappeared when hovering.
<img width="670" alt="screenshot" src="https://user-images.githubusercontent.com/54350573/130349766-e424ae44-a8d6-4f4b-ac88-cc66149864c6.png">

**Comment by mgmeyers** [comment]
@KElee01 I've made some update to the theme, can you update and see if this is still an issue for you?

**Comment by KElee01** [comment]
Thank you for your work! It's been solved, except the blue outline that shows when hovering is a little weird, the lower part is been hiden. Can you solve this later? Thank you so much!
<img width="454" alt="截屏2021-12-31 下午3 57 27" src="https://user-images.githubusercontent.com/54350573/147810898-73c8b780-3d3f-4731-866a-81e380e85660.png">

**Comment by mgmeyers** [comment]
Thanks for bringing this to my attention @KElee01. I've added better styling to this popover. Try updating the theme, and let me know if you have any issues with it.
