### ISSUE TITLE
Cursor visually moving in heading

### ISSUE THREAD

**Issue by tim-hilde** [mgmeyers/obsidian-california-coast-theme#96]
When the cursor is in a heading text and you scroll up and back down, it moves to the left. But only visually, when you type its added at the correct position.

https://user-images.githubusercontent.com/44113468/130620986-0b39272a-60d8-42f0-8a03-c31b33ef0a87.mov

**Comment by mgmeyers** [comment]
@tim-hilde I'm unable to reproduce this. Can you try updating the theme to the latest version and let me know if it's still an issue for you?
