### ISSUE TITLE
[Feature Request] Customize the radius of the window rounded corners

### ISSUE THREAD

**Issue by KElee01** [mgmeyers/obsidian-california-coast-theme#97]
Great theme! But it makes me feel uncomfortable when I found out the radius of the window rounded corners is not as same as that of other apps.

**Comment by mgmeyers** [comment]
@KElee01 Can you clarify what you mean? Maybe a screen shot?

**Comment by KElee01** [comment]
Sorry, I mean, maybe you can give us a choice to use the default radius of the rounded corners of the window.
<img width="281" alt="截屏2021-09-01 上午9 08 21" src="https://user-images.githubusercontent.com/54350573/131595420-5a5a7ae3-2ca5-4e15-95da-1607e55f18f4.png">
The window on the left is Safari, whose radius is about 10px? I guess?
The window on the right is Obsidian, California Coast theme installed, and its rounded corners radius is about 4 px.
I hope there could be a selection to use the default 10px radius rounded corners.

**Comment by mgmeyers** [comment]
@KElee01 what version of the obsidian installer are you on?

<img width="1017" alt="Screen Shot 2021-08-31 at 10 23 19 PM" src="https://user-images.githubusercontent.com/2694747/131616478-d508af49-a6f9-4b50-98bd-d2080ef1cab5.png">

I think 0.12.3 fixed this issue

<img width="212" alt="Screen Shot 2021-08-31 at 10 25 15 PM" src="https://user-images.githubusercontent.com/2694747/131616588-5093bbf7-8879-4701-90f6-d3b9862fbebf.png">

If you're on an older version, you may have to download and install obsidian again.

**Comment by KElee01** [comment]
Yeah, it's fixed after updating, thank you
